# Generated by Django 4.1 on 2023-01-28 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonModel',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('contents', models.TextField()),
                ('date', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CommonFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('file_path', models.TextField()),
                ('common_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_list', to='crawling.commonmodel')),
            ],
        ),
    ]
